### PR TITLE
Adding apps.py and models.py to userpage

### LINKED ISSUE #22: Upload Django models & apps

### PR DESCRIPTION
**Pull request by noah-williams**
I'm adding the apps.py and models.py files to the userpage directory on the main branch.

### CODE REVIEW

**Comment by dl1364** [comment]
Thank you. We also needed this as well!

**Review by dl1364 — APPROVED** [review]
Yeah this is looking good. I don't see that we have to make any changes at the moment!

**Review by Joshua5437 — APPROVED** [review]
Yes, great work Noah. This is why you are the LEADER!!

**Review by jgharris1 — CHANGES_REQUESTED** [review]
an old models.py file was used, please reupload the new edition

**Review by Joshua5437 — COMMENTED** [review]
Great yes

**Review by Joshua5437 — COMMENTED** [review]
Best i've seen yet!

**Pull request closed without merging**
